import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>我的笔记分享</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          我的笔记分享
        </div>

        <div className={styles.grid}>
          <a style={{display:'flex',justifyContent:'center'}} href="https://beian.miit.gov.cn/" target="_blank">豫ICP备2020029001号-6</a>
        </div>
      </main>
    </>
  )
}
